name: pizza-chart-comp-app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
      - appdirs==1.4.4
      - blinker==1.9.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cramjam==2.10.0
      - cycler==0.12.1
      - dash==3.0.4
      - fastparquet==2024.11.0
      - Flask==3.0.3
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - idna==3.10
      - importlib_metadata==8.7.0
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - kiwisolver==1.4.8
      - MarkupSafe==3.0.2
      - narwhals==1.42.1
      - nest-asyncio==1.6.0
      - nfl_data_py==0.3.3
      - packaging==25.0
      - pillow==11.2.1
      - plotly==6.1.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.4
      - retrying==1.3.4
      - six==1.17.0
      - typing_extensions==4.14.0
      - urllib3==2.4.0
      - Werkzeug==3.0.6
      - zipp==3.23.0
      - pyarrow

